name: Build Android APK (TWA)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: Build APK Bubblewrap
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar Bubblewrap CLI
      run: npm install -g @bubblewrap/cli

    - name: Gerar projeto Android (Completamente Automatico)
      run: |
        # Responde "y" para o JDK interno, "y" para o Android SDK interno, e Enter para o resto
        printf "y\ny\n\n\n\n\n\n\n\n\n" | bubblewrap init --manifest=https://AndersonDonizeti.github.io/top-mercado/manifest.json --directory=android --skipPwaValidation

    - name: Build via Gradle
      run: |
        cd android && ./gradlew assembleRelease

    - name: Salvar o APK (Upload)
      uses: actions/upload-artifact@v4
      with:
        name: TopMercado-APK
        path: android/app/build/outputs/apk/release/*.apk
