name: Build Android APK (TWA)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: Build APK Bubblewrap
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Instalar Bubblewrap CLI
      run: npm install -g @bubblewrap/cli

    - name: Inicializar e Construir o APK
      run: |
        # Executa a inicialização respondendo automaticamente com os dados do manifesto
        yes | bubblewrap init --manifest=https://AndersonDonizeti.github.io/top-mercado/manifest.json --directory=android-app
        
        cd android-app
        
        # Atualiza dependências do SDK se necessário
        npx @bubblewrap/cli update || true
        
        # Constrói o APK assinado
        bubblewrap build

    - name: Salvar o APK (Upload)
      uses: actions/upload-artifact@v4
      with:
        name: TopMercado-APK
        path: android-app/app-release-signed.apk
