name: Gerar APK PWA

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Configurar ambiente Android e JDK
        run: |
          bubblewrap init --manifest=https://AndersonDonizeti.github.io/top-mercado/manifest.json --directory=android-app
          cd android-app
          npx @bubblewrap/cli update

      - name: Compilar o APK
        run: |
          cd android-app
          npx @bubblewrap/cli build

      - name: Salvar o APK gerado
        uses: actions/upload-artifact@v4
        with:
          name: app-top-mercado-apk
          path: android-app/app-release-signed.apk
